import {
  drillTitle,
  type DrillLevel,
  type DrillTemplate,
  type DrillType,
  type LicenseLevel,
  type MomentOfGame,
  type PlayerCount,
  type SetupDiagram,
  type SkillLevel,
} from "@/lib/club/catalog";

type AgeBand = "U8-U10" | "U11-U13" | "U14-U16" | "senior";

type DrillInput = {
  id: string;
  moment: MomentOfGame;
  type: DrillType;
  focus: string;
  playerSetup: string;
  constraint: string;
  license: LicenseLevel;
  ageBand: AgeBand;
  diagram: SetupDiagram;
  minutes: number;
  length: number;
  width: number;
  workRest: string;
  repetitions: number;
  players: PlayerCount;
  equipment: string[];
  tags: string[];
  pitchSetup: string;
  instructions: string;
  coachingPoints: string[];
  progressions: string[];
};

function levelFor(ageBand: AgeBand, license: LicenseLevel): DrillLevel {
  if (license === "UEFA Pro") return "Pro";
  if (ageBand === "senior" || license === "UEFA A") return "Senior Amateur";
  if (ageBand === "U14-U16") return "Youth U13-16";
  if (ageBand === "U8-U10") return "Grassroots";
  return "Youth U9-12";
}

/** One library drill for each age from U6 to U13, in each skill. Content stays the UEFA record. */
const PLACEMENT: Record<string, { youthAge: number; skillLevel: SkillLevel }> = {
  drill_uefa_ip_wu: { youthAge: 6, skillLevel: "Beginner" },
  drill_uefa_t2d_wu: { youthAge: 7, skillLevel: "Beginner" },
  drill_uefa_t2a_wu: { youthAge: 8, skillLevel: "Beginner" },
  drill_uefa_oop_tp: { youthAge: 9, skillLevel: "Beginner" },
  drill_uefa_t2a_tp: { youthAge: 10, skillLevel: "Beginner" },
  drill_uefa_oop_wu: { youthAge: 11, skillLevel: "Beginner" },
  drill_uefa_ip_tp: { youthAge: 12, skillLevel: "Beginner" },
  drill_uefa_t2d_tp: { youthAge: 13, skillLevel: "Beginner" },
  drill_uefa_att_094: { youthAge: 6, skillLevel: "Intermediate" },
  drill_uefa_ip_sp: { youthAge: 7, skillLevel: "Intermediate" },
  drill_uefa_t2a_sp: { youthAge: 8, skillLevel: "Intermediate" },
  drill_uefa_oop_sp: { youthAge: 9, skillLevel: "Intermediate" },
  drill_uefa_t2a_ssg: { youthAge: 10, skillLevel: "Intermediate" },
  drill_uefa_oop_ssg: { youthAge: 11, skillLevel: "Intermediate" },
  drill_uefa_t2d_ssg: { youthAge: 12, skillLevel: "Intermediate" },
  drill_uefa_ip_ssg: { youthAge: 13, skillLevel: "Intermediate" },
  drill_uefa_t2a_pop: { youthAge: 6, skillLevel: "Professional" },
  drill_uefa_oop_pop: { youthAge: 7, skillLevel: "Professional" },
  drill_uefa_ip_pop: { youthAge: 8, skillLevel: "Professional" },
  drill_uefa_t2d_pop: { youthAge: 9, skillLevel: "Professional" },
  drill_uefa_oop_11: { youthAge: 10, skillLevel: "Professional" },
  drill_uefa_ip_11: { youthAge: 11, skillLevel: "Professional" },
  drill_uefa_t2a_11: { youthAge: 12, skillLevel: "Professional" },
  drill_uefa_t2d_11: { youthAge: 13, skillLevel: "Professional" },
};

function drill(input: DrillInput): DrillTemplate {
  const place = PLACEMENT[input.id];
  if (!place) throw new Error(`Missing age and skill for ${input.id}`);
  const outfield = input.players.attackers + input.players.defenders + input.players.neutrals;
  return {
    id: input.id,
    title: drillTitle(input.type, input.focus, input.playerSetup, input.constraint),
    isClubOfficial: true,
    targetAgeGroup: input.ageBand,
    moment: input.moment,
    drillType: input.type,
    level: levelFor(input.ageBand, input.license),
    focus: input.focus,
    playerSetup: input.playerSetup,
    constraint: input.constraint,
    dimensions: `${input.length}x${input.width}m`,
    workRest: input.workRest,
    repetitions: input.repetitions,
    players: { ...input.players },
    equipment: input.equipment,
    diagram: input.diagram,
    pitchSetup: input.pitchSetup,
    instructions: input.instructions,
    coachingPoints: input.coachingPoints,
    progressions: input.progressions,
    tags: input.tags,
    licenseLevel: input.license,
    ageBand: input.ageBand,
    youthAge: place.youthAge,
    skillLevel: place.skillLevel,
    minPlayers: outfield,
    maxPlayers: outfield,
    pitchLengthM: input.length,
    pitchWidthM: input.width,
    defaultDurationSeconds: input.minutes * 60,
    videoUrl: "",
    videoName: "",
  };
}

const players = (attackers: number, defenders = 0, neutrals = 0, goalkeepers = 0): PlayerCount => ({
  attackers,
  defenders,
  neutrals,
  goalkeepers,
});

/** UEFA training drill library. Names follow type, focus, player setup, and constraint. */
export const clubLibrary: DrillTemplate[] = [
  drill({
    id: "drill_uefa_ip_wu",
    moment: "IP",
    type: "WU",
    focus: "Ball Mastery",
    playerSetup: "Pairs",
    constraint: "Both Feet",
    license: "Grassroots",
    ageBand: "U8-U10",
    diagram: "gates",
    minutes: 10,
    length: 20,
    width: 20,
    workRest: "2:1",
    repetitions: 4,
    players: players(2),
    equipment: ["Balls", "Cones"],
    tags: ["warm-up", "ball mastery", "in possession"],
    pitchSetup: "20x20m grid. One ball per pair.",
    instructions: "Players dribble freely, then pass and move on the coach call. Every pass uses the other foot.",
    coachingPoints: ["Ball close when turning", "Head up between touches", "Pass to the back foot"],
    progressions: ["One foot only.", "Add a light defender who can steal a loose ball."],
  }),
  drill({
    id: "drill_uefa_ip_tp",
    moment: "IP",
    type: "TP",
    focus: "Build-up Play",
    playerSetup: "4 Players",
    constraint: "2 Touch",
    license: "UEFA C",
    ageBand: "U11-U13",
    diagram: "square",
    minutes: 12,
    length: 20,
    width: 15,
    workRest: "3:1",
    repetitions: 3,
    players: players(4),
    equipment: ["Cones", "Balls"],
    tags: ["build-up", "passing", "in possession"],
    pitchSetup: "20x15m rectangle. Four players, one on each side.",
    instructions: "Play two-touch around the rectangle. The receiver checks off the cone, opens the body, and plays the next pass forward.",
    coachingPoints: ["Scan before the ball arrives", "First touch out of pressure", "Pass weight to the next player"],
    progressions: ["Limit the practice to one touch.", "Add a passive defender on one side."],
  }),
  drill({
    id: "drill_uefa_ip_sp",
    moment: "IP",
    type: "SP",
    focus: "Creating Chances",
    playerSetup: "3v2",
    constraint: "Finish",
    license: "UEFA B",
    ageBand: "U14-U16",
    diagram: "channel",
    minutes: 15,
    length: 30,
    width: 25,
    workRest: "3:1",
    repetitions: 4,
    players: players(3, 2, 0, 1),
    equipment: ["Balls", "Full size goal", "Bibs (2 colors)"],
    tags: ["chance", "overload", "finishing"],
    pitchSetup: "30x25m channel to one goal. Three attackers against two defenders and a goalkeeper.",
    instructions: "The three combine to create a shot. They must play through the two before finishing. Restart from the coach if the move stalls.",
    coachingPoints: ["Play the free player early", "Third-man run beyond the ball", "Finish across the keeper"],
    progressions: ["Limit the attackers to two touches.", "The defenders score in a mini goal if they win it."],
  }),
  drill({
    id: "drill_uefa_ip_pop",
    moment: "IP",
    type: "PoP",
    focus: "Playing Through Lines",
    playerSetup: "8v6",
    constraint: "Half Pitch",
    license: "UEFA B",
    ageBand: "U14-U16",
    diagram: "press",
    minutes: 18,
    length: 50,
    width: 40,
    workRest: "4:1",
    repetitions: 3,
    players: players(8, 6, 0, 1),
    equipment: ["Bibs (2 colors)", "Balls", "Full size goal", "Cones"],
    tags: ["phase of play", "build-up", "lines"],
    pitchSetup: "Half pitch. Eight in possession against a mid-block of six, plus a goalkeeper.",
    instructions: "Build from the goalkeeper and play through the mid-block. A point is scored by a pass that breaks the line into a runner.",
    coachingPoints: ["Split the centre-backs", "Receive between the lines on the half-turn", "Play forward when the picture is on"],
    progressions: ["The block starts one line higher.", "The team in possession has eight seconds to break a line."],
  }),
  drill({
    id: "drill_uefa_ip_ssg",
    moment: "IP",
    type: "SSG",
    focus: "Playing Through Lines",
    playerSetup: "6v6+2",
    constraint: "Neutral Targets",
    license: "UEFA B",
    ageBand: "U14-U16",
    diagram: "rondo",
    minutes: 20,
    length: 40,
    width: 30,
    workRest: "4:1",
    repetitions: 4,
    players: players(6, 6, 2, 0),
    equipment: ["Bibs (3 colors)", "Ball", "Cones"],
    tags: ["small-sided game", "lines", "neutrals"],
    pitchSetup: "40x30m area. 6v6 inside, with one neutral target at each end.",
    instructions: "Play 6v6 inside the area. The two neutral players act as targets at opposite ends. A point is scored by playing from one neutral to the other without losing the ball. After scoring, keep the ball and attack the other way.",
    coachingPoints: ["Play forward early and break a line", "Move off the ball to open a passing lane", "Counter-press within three seconds of a loss"],
    progressions: ["Limit players to two touches.", "Remove the neutrals and add two full-size goals."],
  }),
  drill({
    id: "drill_uefa_ip_11",
    moment: "IP",
    type: "11v11",
    focus: "Breaking the Mid-Block",
    playerSetup: "11v11",
    constraint: "Final Third",
    license: "UEFA A",
    ageBand: "senior",
    diagram: "channel",
    minutes: 20,
    length: 100,
    width: 60,
    workRest: "2:1",
    repetitions: 2,
    players: players(11, 11, 0, 2),
    equipment: ["Bibs (2 colors)", "Balls", "Full size goals"],
    tags: ["11v11", "mid-block", "tactical"],
    pitchSetup: "Full pitch. Both teams in a match shape.",
    instructions: "The team in possession must break the mid-block before shooting. A goal from a direct regain does not count.",
    coachingPoints: ["Width before the switch", "A runner beyond the line of the ball", "Rest defence stays connected"],
    progressions: ["The block defends one line deeper.", "A goal only counts if the assist broke the block."],
  }),
  drill({
    id: "drill_uefa_oop_wu",
    moment: "OOP",
    type: "WU",
    focus: "Defensive Shape",
    playerSetup: "6 Players",
    constraint: "Body Shape",
    license: "UEFA C",
    ageBand: "U11-U13",
    diagram: "lanes",
    minutes: 8,
    length: 20,
    width: 20,
    workRest: "2:1",
    repetitions: 4,
    players: players(0, 6),
    equipment: ["Cones"],
    tags: ["warm-up", "defending", "shape"],
    pitchSetup: "20x20m square. Six players in two lines of three.",
    instructions: "The six shuffle as a line. On the call they drop, jump, or slide together without breaking the distances.",
    coachingPoints: ["See the ball and the player", "Distances stay even", "First step is sideways, not a dive"],
    progressions: ["Add a ball for the line to face.", "One player steps out and the line covers."],
  }),
  drill({
    id: "drill_uefa_oop_tp",
    moment: "OOP",
    type: "TP",
    focus: "Pressing Angle",
    playerSetup: "Pairs",
    constraint: "Arrival Line",
    license: "UEFA C",
    ageBand: "U11-U13",
    diagram: "press",
    minutes: 10,
    length: 15,
    width: 10,
    workRest: "2:1",
    repetitions: 6,
    players: players(1, 1),
    equipment: ["Cones", "Balls"],
    tags: ["pressing", "angle", "defending"],
    pitchSetup: "15x10m lane. One attacker with a ball, one defender.",
    instructions: "The defender closes on a curved run and arrives side-on. They show the attacker one way and do not dive in.",
    coachingPoints: ["Speed on the approach, then slow", "Body shape forces one direction", "Do not overrun the ball"],
    progressions: ["The attacker can turn if the angle is wrong.", "Add a second defender as cover."],
  }),
  drill({
    id: "drill_uefa_oop_sp",
    moment: "OOP",
    type: "SP",
    focus: "High Press",
    playerSetup: "4v3",
    constraint: "One Trigger",
    license: "UEFA B",
    ageBand: "U14-U16",
    diagram: "press",
    minutes: 15,
    length: 30,
    width: 25,
    workRest: "3:1",
    repetitions: 4,
    players: players(3, 4, 0, 1),
    equipment: ["Bibs (2 colors)", "Balls", "Full size goal"],
    tags: ["high press", "trigger", "out of possession"],
    pitchSetup: "30x25m. Four press a goalkeeper and three, who start with the ball.",
    instructions: "The press jumps only on a backwards pass. If the ball goes wide, the four recover in a line.",
    coachingPoints: ["One trigger, the whole line jumps", "Cover the inside pass", "Recover together if the press is broken"],
    progressions: ["Add a second trigger: a poor first touch.", "The three score by playing through the press into a mini goal."],
  }),
  drill({
    id: "drill_uefa_oop_pop",
    moment: "OOP",
    type: "PoP",
    focus: "Mid-Block",
    playerSetup: "8v7",
    constraint: "Stay Compact",
    license: "UEFA B",
    ageBand: "U14-U16",
    diagram: "press",
    minutes: 18,
    length: 50,
    width: 40,
    workRest: "4:1",
    repetitions: 3,
    players: players(8, 7, 0, 1),
    equipment: ["Bibs (2 colors)", "Balls", "Full size goal"],
    tags: ["mid-block", "compact", "phase of play"],
    pitchSetup: "Half pitch. Seven defend in a mid-block against eight.",
    instructions: "The seven protect the centre and force play wide. They step out only when the ball is played backwards or into a marked player.",
    coachingPoints: ["Distances between the lines stay short", "Show play away from the centre", "The far winger tucks in"],
    progressions: ["The block starts higher.", "A goal for the eight only counts from a central pass."],
  }),
  drill({
    id: "drill_uefa_oop_ssg",
    moment: "OOP",
    type: "SSG",
    focus: "Low Block",
    playerSetup: "5v5+GK",
    constraint: "Protect the Box",
    license: "UEFA B",
    ageBand: "U14-U16",
    diagram: "channel",
    minutes: 16,
    length: 35,
    width: 30,
    workRest: "4:1",
    repetitions: 3,
    players: players(5, 5, 0, 2),
    equipment: ["Bibs (2 colors)", "Ball", "Full size goals"],
    tags: ["low block", "small-sided game", "box"],
    pitchSetup: "35x30m with two full goals. Each team defends a low block when out of possession.",
    instructions: "Both teams drop to the edge of the box when they lose the shape of the attack. A goal counts only if the defence was set before the shot.",
    coachingPoints: ["Protect the centre of the box", "Attack the cross, do not watch it", "The keeper owns the six-yard box"],
    progressions: ["Shots from outside the box do not count.", "The block must be four players or the goal is disallowed."],
  }),
  drill({
    id: "drill_uefa_oop_11",
    moment: "OOP",
    type: "11v11",
    focus: "Defending the Box",
    playerSetup: "11v11",
    constraint: "Zonal",
    license: "UEFA A",
    ageBand: "senior",
    diagram: "corner",
    minutes: 20,
    length: 100,
    width: 60,
    workRest: "2:1",
    repetitions: 2,
    players: players(11, 11, 0, 2),
    equipment: ["Bibs (2 colors)", "Balls", "Full size goals"],
    tags: ["11v11", "box", "zonal"],
    pitchSetup: "Full pitch. The defending team uses a zonal box when the ball is wide.",
    instructions: "When the ball is in the wide channel, the defending team sets a zonal box. They clear to the side, then set the rest defence.",
    coachingPoints: ["Attack the ball", "First clear is wide", "The rest defence is set before the second ball"],
    progressions: ["Man-mark the near post.", "The attacking team has a short corner option."],
  }),
  drill({
    id: "drill_uefa_t2a_wu",
    moment: "T2A",
    type: "WU",
    focus: "First Pass Forward",
    playerSetup: "Pairs",
    constraint: "Scan",
    license: "UEFA C",
    ageBand: "U11-U13",
    diagram: "lanes",
    minutes: 8,
    length: 20,
    width: 15,
    workRest: "2:1",
    repetitions: 6,
    players: players(2),
    equipment: ["Balls", "Cones"],
    tags: ["transition", "first pass", "warm-up"],
    pitchSetup: "20x15m lane. Pairs facing forward.",
    instructions: "On the call, the player in possession scans and plays the first pass forward to a partner who has already started the run.",
    coachingPoints: ["Look before receiving", "The first pass is forward", "The runner starts as the ball is won"],
    progressions: ["The pass must be one touch.", "Add a recovering defender behind the passer."],
  }),
  drill({
    id: "drill_uefa_t2a_tp",
    moment: "T2A",
    type: "TP",
    focus: "Secure the First Pass",
    playerSetup: "3 Players",
    constraint: "Forward",
    license: "UEFA C",
    ageBand: "U11-U13",
    diagram: "square",
    minutes: 10,
    length: 20,
    width: 15,
    workRest: "3:1",
    repetitions: 4,
    players: players(3),
    equipment: ["Balls", "Cones"],
    tags: ["first pass", "support", "transition to attack"],
    pitchSetup: "20x15m. Three players in a triangle.",
    instructions: "The player who receives turns and plays forward to the highest player. The third player supports underneath in case the forward pass is not on.",
    coachingPoints: ["Support underneath the ball", "Forward pass if the picture is on", "Body shape to play the other way"],
    progressions: ["The forward pass is compulsory.", "Add a passive defender on the highest player."],
  }),
  drill({
    id: "drill_uefa_t2a_sp",
    moment: "T2A",
    type: "SP",
    focus: "Counter Attack",
    playerSetup: "3v2",
    constraint: "6 Seconds",
    license: "UEFA B",
    ageBand: "U14-U16",
    diagram: "channel",
    minutes: 14,
    length: 40,
    width: 25,
    workRest: "3:1",
    repetitions: 6,
    players: players(3, 2, 0, 1),
    equipment: ["Balls", "Full size goal", "Bibs (2 colors)"],
    tags: ["counter-attack", "transition to attack", "overload"],
    pitchSetup: "40x25m to one goal. The three start by winning the ball at the halfway line.",
    instructions: "Win the ball and score within six seconds. If the move stalls, the attack is over and the practice resets.",
    coachingPoints: ["First pass forward", "Run beyond the ball", "Finish before the extra defender arrives"],
    progressions: ["Shorten the count to five seconds.", "A fourth defender can recover from behind."],
  }),
  drill({
    id: "drill_uefa_t2a_pop",
    moment: "T2A",
    type: "PoP",
    focus: "Attack the Space",
    playerSetup: "6v4+GK",
    constraint: "Wide",
    license: "UEFA B",
    ageBand: "U14-U16",
    diagram: "overlap",
    minutes: 16,
    length: 50,
    width: 40,
    workRest: "4:1",
    repetitions: 4,
    players: players(6, 4, 0, 1),
    equipment: ["Bibs (2 colors)", "Balls", "Full size goal", "Cones"],
    tags: ["transition", "width", "phase of play"],
    pitchSetup: "Half pitch. Six attack four and a goalkeeper after a regain in their own half.",
    instructions: "The regain is the start. The six attack the space in front of them, using the wide player who is already high.",
    coachingPoints: ["Play into the space, not the feet", "The wide player stays high", "A cross or a shot before the block is set"],
    progressions: ["The four can counter-press for three seconds.", "The attack must use the weak side."],
  }),
  drill({
    id: "drill_uefa_t2a_ssg",
    moment: "T2A",
    type: "SSG",
    focus: "Counter Attack",
    playerSetup: "4v4+GK",
    constraint: "Two Goals",
    license: "UEFA B",
    ageBand: "U14-U16",
    diagram: "channel",
    minutes: 16,
    length: 40,
    width: 30,
    workRest: "4:1",
    repetitions: 3,
    players: players(4, 4, 0, 2),
    equipment: ["Bibs (2 colors)", "Ball", "Full size goals"],
    tags: ["counter-attack", "small-sided game", "two goals"],
    pitchSetup: "40x30m with a goal at each end.",
    instructions: "A goal starts from a regain. The team that scores from a move longer than eight seconds does not count the goal.",
    coachingPoints: ["Secure, then play forward", "Numbers beyond the ball", "Restart quickly after the goal"],
    progressions: ["Eight seconds becomes six.", "Both teams leave two players as rest defence."],
  }),
  drill({
    id: "drill_uefa_t2a_11",
    moment: "T2A",
    type: "11v11",
    focus: "Transition Attack",
    playerSetup: "11v11",
    constraint: "8 Seconds",
    license: "UEFA A",
    ageBand: "senior",
    diagram: "channel",
    minutes: 20,
    length: 100,
    width: 60,
    workRest: "2:1",
    repetitions: 2,
    players: players(11, 11, 0, 2),
    equipment: ["Bibs (2 colors)", "Balls", "Full size goals"],
    tags: ["11v11", "counter-attack", "transition to attack"],
    pitchSetup: "Full pitch. Match shapes.",
    instructions: "After a regain, the team in possession attacks the far goal within eight seconds. If they keep the ball longer, they must build and the counter is over.",
    coachingPoints: ["The first pass breaks the line", "Forward runs are timed with the pass", "The rest defence does not all join"],
    progressions: ["The count drops to six seconds.", "A goal from the counter is worth two."],
  }),
  drill({
    id: "drill_uefa_t2d_wu",
    moment: "T2D",
    type: "WU",
    focus: "React to the Loss",
    playerSetup: "Pairs",
    constraint: "First Step",
    license: "UEFA C",
    ageBand: "U11-U13",
    diagram: "gates",
    minutes: 8,
    length: 15,
    width: 15,
    workRest: "2:1",
    repetitions: 6,
    players: players(2),
    equipment: ["Balls", "Cones"],
    tags: ["reaction", "counter-press", "warm-up"],
    pitchSetup: "15x15m grid. Pairs passing.",
    instructions: "On the call 'lost', the passer sprints to the ball and the receiver shields it. The first step is toward the ball, not back.",
    coachingPoints: ["React in the first second", "Sprint to the ball, then arrive under control", "The nearest player goes"],
    progressions: ["The receiver may turn and escape.", "A third player joins the press."],
  }),
  drill({
    id: "drill_uefa_t2d_tp",
    moment: "T2D",
    type: "TP",
    focus: "Counter-Press Shape",
    playerSetup: "4 Players",
    constraint: "Cut the Lane",
    license: "UEFA B",
    ageBand: "U14-U16",
    diagram: "square",
    minutes: 10,
    length: 15,
    width: 15,
    workRest: "3:1",
    repetitions: 4,
    players: players(4),
    equipment: ["Cones", "Ball"],
    tags: ["counter-press", "body shape", "lanes"],
    pitchSetup: "15x15m square. Four players, one ball.",
    instructions: "When the pass is cut off by the coach, the four set a counter-press shape: one presses the ball and the others cut the nearest passing lanes.",
    coachingPoints: ["Body shape closes the centre", "The presser shows the ball one way", "The covering players see both the ball and their lane"],
    progressions: ["The shape must be set within three seconds.", "Add a fifth player as the free outlet."],
  }),
  drill({
    id: "drill_uefa_att_094",
    moment: "T2D",
    type: "SP",
    focus: "Counter Press",
    playerSetup: "4v2",
    constraint: "3 Seconds",
    license: "UEFA B",
    ageBand: "U14-U16",
    diagram: "rondo",
    minutes: 15,
    length: 15,
    width: 15,
    workRest: "3:1",
    repetitions: 4,
    players: players(4, 2),
    equipment: ["Cones", "Ball", "Bibs (2 colors)"],
    tags: ["rondo", "counter-press", "transition"],
    pitchSetup: "15x15m square in the central channel. Four outside, two inside.",
    instructions: "Four possession players keep the ball in a tight square against two defenders. On a turnover, the four must counter-press and win the ball back within 3 seconds.",
    coachingPoints: [
      "Immediate reaction on ball loss in the first 3 seconds.",
      "Body shape cuts off the central passing lanes.",
      "Quick transition once the ball is lost.",
    ],
    progressions: [
      "Limit the possession players to one touch.",
      "If the defenders win the ball, they score by passing into mini goals.",
    ],
  }),
  drill({
    id: "drill_uefa_t2d_pop",
    moment: "T2D",
    type: "PoP",
    focus: "Gegenpress",
    playerSetup: "8v6",
    constraint: "Win it Back",
    license: "UEFA A",
    ageBand: "U14-U16",
    diagram: "press",
    minutes: 16,
    length: 50,
    width: 40,
    workRest: "3:1",
    repetitions: 4,
    players: players(8, 6, 0, 1),
    equipment: ["Bibs (2 colors)", "Balls", "Full size goal"],
    tags: ["gegenpress", "counter-press", "phase of play"],
    pitchSetup: "Half pitch. Eight attack, then counter-press a six who have just won the ball.",
    instructions: "The eight attack the goal. The moment they lose the ball, the nearest three press and the rest cut the forward passes. They have five seconds to win it back.",
    coachingPoints: ["The nearest player presses", "The next players cut the forward pass", "If the five seconds pass, the team drops"],
    progressions: ["Five seconds becomes three.", "The six score in the big goal if they break the press."],
  }),
  drill({
    id: "drill_uefa_t2d_ssg",
    moment: "T2D",
    type: "SSG",
    focus: "Counter Pressing",
    playerSetup: "6v6+GK",
    constraint: "4 Goal Game",
    license: "UEFA B",
    ageBand: "U14-U16",
    diagram: "gates",
    minutes: 18,
    length: 40,
    width: 30,
    workRest: "4:1",
    repetitions: 3,
    players: players(6, 6, 0, 2),
    equipment: ["Bibs (2 colors)", "Ball", "Mini goals"],
    tags: ["counter-press", "small-sided game", "four goals"],
    pitchSetup: "40x30m with two mini goals on each end line.",
    instructions: "Play 6v6 plus goalkeepers. After a loss, the team has four seconds to counter-press. If they win it back and score in either mini goal, the goal counts double.",
    coachingPoints: ["Press the ball and the forward pass", "The goalkeepers organise the rest", "A double goal only comes from the regain"],
    progressions: ["The counter-press window is three seconds.", "Remove one mini goal so the press has a narrower target."],
  }),
  drill({
    id: "drill_uefa_t2d_11",
    moment: "T2D",
    type: "11v11",
    focus: "Rest Defence",
    playerSetup: "11v11",
    constraint: "Delay",
    license: "UEFA A",
    ageBand: "senior",
    diagram: "press",
    minutes: 20,
    length: 100,
    width: 60,
    workRest: "2:1",
    repetitions: 2,
    players: players(11, 11, 0, 2),
    equipment: ["Bibs (2 colors)", "Balls", "Full size goals"],
    tags: ["11v11", "rest defence", "transition to defence"],
    pitchSetup: "Full pitch. Both teams keep a rest-defence shape while attacking.",
    instructions: "On a loss, the three nearest players delay the counter. The rest recover behind the ball. A counter goal against a team that failed to delay does not restart until the coach stops the practice.",
    coachingPoints: ["Delay, do not dive in", "Protect the centre", "Recover behind the ball before jumping again"],
    progressions: ["The counter has six seconds.", "One of the three may jump if the first pass is backwards."],
  }),
];
