import { drillTitle, type DrillLevel, type DrillTemplate, type DrillType, type MomentOfGame, type PlayerCount, type SetupDiagram } from "@/lib/club/catalog";

type DrillInput = {
  id: string;
  age: string;
  moment: MomentOfGame;
  type: DrillType;
  focus: string;
  playerSetup: string;
  constraint: string;
  level: DrillLevel;
  diagram: SetupDiagram;
  minutes: number;
  dimensions: string;
  workRest: string;
  repetitions: number;
  players: PlayerCount;
  equipment: string[];
  pitchSetup: string;
  instructions: string;
  coachingPoints: string[];
  progressions: string[];
};

function drill(input: DrillInput): DrillTemplate {
  const title = drillTitle(input.type, input.focus, input.playerSetup, input.constraint);
  return {
    id: input.id,
    title,
    isClubOfficial: true,
    targetAgeGroup: input.age,
    moment: input.moment,
    drillType: input.type,
    level: input.level,
    focus: input.focus,
    playerSetup: input.playerSetup,
    constraint: input.constraint,
    dimensions: input.dimensions,
    workRest: input.workRest,
    repetitions: input.repetitions,
    players: { ...input.players },
    equipment: input.equipment,
    diagram: input.diagram,
    pitchSetup: input.pitchSetup,
    instructions: input.instructions,
    coachingPoints: input.coachingPoints,
    progressions: input.progressions,
    defaultDurationSeconds: input.minutes * 60,
    videoUrl: "",
    videoName: "",
  };
}

const none: PlayerCount = { attackers: 0, defenders: 0, neutrals: 0, goalkeepers: 0 };
const count = (attackers: number, defenders = 0, neutrals = 0, goalkeepers = 0): PlayerCount => ({
  attackers,
  defenders,
  neutrals,
  goalkeepers,
});

/** Official club drill library, named with the UEFA formula. */
export const clubLibrary: DrillTemplate[] = [
  drill({
    id: "dr-01",
    age: "Under 11",
    moment: "IP",
    type: "TP",
    focus: "First Touch",
    playerSetup: "Square",
    constraint: "2 Touch",
    level: "Youth U9-12",
    diagram: "square",
    minutes: 6,
    dimensions: "10x10m",
    workRest: "6 min block",
    repetitions: 1,
    players: count(4),
    equipment: ["Cones", "Ball"],
    pitchSetup: "10m square, one ball, a cone on each corner.",
    instructions: "Two-touch around the square. The receiver checks off the cone, opens their body, and passes to the next corner.",
    coachingPoints: ["First touch out of pressure", "Head up before the pass", "Pass into the back foot"],
    progressions: ["Limit the square to one touch.", "Add one defender inside the square."],
  }),
  drill({
    id: "dr-02",
    age: "Under 11",
    moment: "IP",
    type: "TP",
    focus: "Wall Pass",
    playerSetup: "Pairs",
    constraint: "On the Move",
    level: "Youth U9-12",
    diagram: "square",
    minutes: 6,
    dimensions: "8x8m",
    workRest: "6 min block",
    repetitions: 1,
    players: count(4),
    equipment: ["Cones", "Balls"],
    pitchSetup: "8m square with a partner on each side.",
    instructions: "Play a wall pass, then take the return on the move into the next gap.",
    coachingPoints: ["Firm first pass", "Move as the ball travels", "Receive side-on"],
    progressions: ["One touch on the wall pass.", "Add a chaser behind the ball carrier."],
  }),
  drill({
    id: "dr-03",
    age: "Under 13",
    moment: "IP",
    type: "TP",
    focus: "Half Turn",
    playerSetup: "Line of 3",
    constraint: "Play Forward",
    level: "Youth U13-16",
    diagram: "square",
    minutes: 6,
    dimensions: "8m spacings",
    workRest: "6 min block",
    repetitions: 1,
    players: count(4),
    equipment: ["Cones", "Balls"],
    pitchSetup: "Three cones in a line, 8m apart, one server.",
    instructions: "Check away, then receive on the half-turn and play forward with the second touch.",
    coachingPoints: ["Scan before the ball arrives", "Back foot first", "Open the body to the next pass"],
    progressions: ["Receive with one touch and play forward.", "Add a passive defender on the shoulder."],
  }),
  drill({
    id: "dr-04",
    age: "Under 13",
    moment: "IP",
    type: "SP",
    focus: "1v1 to Goal",
    playerSetup: "1v1",
    constraint: "Finish Early",
    level: "Youth U13-16",
    diagram: "channel",
    minutes: 8,
    dimensions: "Half pitch channel",
    workRest: "45 sec work / 30 sec rest",
    repetitions: 6,
    players: count(1, 1, 0, 1),
    equipment: ["Balls", "Full size goal", "Cones"],
    pitchSetup: "Channel from halfway to one goal. Balls at the start cone.",
    instructions: "Attacker receives facing forward and tries to score. Defender delays, then tackles on a heavy touch.",
    coachingPoints: ["Attack the front foot", "Finish early", "Defender stays side-on"],
    progressions: ["Start the attacker with their back to goal.", "Allow a second attacker as a bounce."],
  }),
  drill({
    id: "dr-05",
    age: "Under 11",
    moment: "IP",
    type: "WU",
    focus: "Dribble Gates",
    playerSetup: "One Player",
    constraint: "Both Feet",
    level: "Youth U9-12",
    diagram: "gates",
    minutes: 6,
    dimensions: "20x20m",
    workRest: "45 sec work / 30 sec rest",
    repetitions: 4,
    players: count(1),
    equipment: ["Cones", "Ball"],
    pitchSetup: "Six small gates scattered in a 20m box.",
    instructions: "Dribble through as many gates as possible. Change foot and direction at each gate.",
    coachingPoints: ["Ball close on the turn", "Head up between gates", "Use both feet"],
    progressions: ["Weak foot only.", "Add a light defender who may steal a loose ball."],
  }),
  drill({
    id: "dr-06",
    age: "Under 15",
    moment: "IP",
    type: "SP",
    focus: "Cutback Finish",
    playerSetup: "Wide Runner",
    constraint: "First Time",
    level: "Youth U13-16",
    diagram: "channel",
    minutes: 8,
    dimensions: "Half pitch",
    workRest: "8 min block",
    repetitions: 1,
    players: count(2, 0, 0, 1),
    equipment: ["Balls", "Full size goal", "Cones"],
    pitchSetup: "Half pitch, one goal, a cone on the byline for the crosser.",
    instructions: "Wide player drives to the byline and cuts the ball back. The runner finishes first time.",
    coachingPoints: ["Cross along the ground", "Time the run", "Finish across the keeper"],
    progressions: ["Add a recovering defender.", "Ask for a cutback or an early cross."],
  }),
  drill({
    id: "dr-07",
    age: "Under 13",
    moment: "IP",
    type: "TP",
    focus: "Weak Foot",
    playerSetup: "Pairs",
    constraint: "Weak Foot Only",
    level: "Youth U13-16",
    diagram: "lanes",
    minutes: 6,
    dimensions: "15m lanes",
    workRest: "6 min block",
    repetitions: 1,
    players: count(8),
    equipment: ["Cones", "Balls"],
    pitchSetup: "Four 15m lanes. One ball per pair.",
    instructions: "Pass and follow up the lane using the weak foot only. Switch lanes on the coach call.",
    coachingPoints: ["Ankle locked", "Non-kicking foot beside the ball", "Pass weight to the next player"],
    progressions: ["One touch with the weak foot.", "Receive with one foot and pass with the other."],
  }),
  drill({
    id: "dr-08",
    age: "Under 15",
    moment: "IP",
    type: "TP",
    focus: "Moving Finish",
    playerSetup: "Striker",
    constraint: "1 Touch",
    level: "Youth U13-16",
    diagram: "channel",
    minutes: 8,
    dimensions: "Penalty area",
    workRest: "8 min block",
    repetitions: 1,
    players: count(2, 0, 0, 1),
    equipment: ["Balls", "Full size goal"],
    pitchSetup: "Penalty area, server on the side, balls in a pile.",
    instructions: "Server rolls the ball across the box. Striker meets it and finishes with one touch.",
    coachingPoints: ["Set the standing foot", "Head still", "Pick a corner before contact"],
    progressions: ["Finish on the bounce.", "Add a passive defender on the line of the shot."],
  }),
  drill({
    id: "dr-09",
    age: "Under 13",
    moment: "IP",
    type: "Rondo",
    focus: "Tight Spaces",
    playerSetup: "4v2",
    constraint: "2 Touch",
    level: "Youth U13-16",
    diagram: "rondo",
    minutes: 6,
    dimensions: "12x12m",
    workRest: "3 min work / 1 min rest",
    repetitions: 2,
    players: count(4, 2),
    equipment: ["Cones", "Ball", "Bibs (2 colors)"],
    pitchSetup: "12m square. Four outside, two inside.",
    instructions: "Outside players keep the ball in two touches. A defender who wins it swaps with the passer.",
    coachingPoints: ["Body shape to play forward", "Split the two defenders", "Press as soon as the ball is lost"],
    progressions: ["One touch maximum.", "Add a neutral who can play for the team in possession."],
  }),
  drill({
    id: "dr-10",
    age: "Under 15",
    moment: "IP",
    type: "SP",
    focus: "Possession",
    playerSetup: "5v3",
    constraint: "Win and Keep",
    level: "Youth U13-16",
    diagram: "rondo",
    minutes: 8,
    dimensions: "20x20m",
    workRest: "4 min work / 1 min rest",
    repetitions: 2,
    players: count(5, 3),
    equipment: ["Cones", "Ball", "Bibs (2 colors)"],
    pitchSetup: "20m box. Five keepers of the ball, three pressing.",
    instructions: "The five keep possession. If the three win it and make three passes, the roles swap.",
    coachingPoints: ["Angles of support", "Play away from pressure", "Compact press"],
    progressions: ["Limit the five to two touches.", "Score by splitting the three with a forward pass."],
  }),
  drill({
    id: "dr-11",
    age: "Under 15",
    moment: "IP",
    type: "PoP",
    focus: "Overlap and Cross",
    playerSetup: "Half Pitch",
    constraint: "Wide",
    level: "Youth U13-16",
    diagram: "overlap",
    minutes: 8,
    dimensions: "Half pitch",
    workRest: "8 min block",
    repetitions: 1,
    players: count(4, 3, 0, 1),
    equipment: ["Cones", "Balls", "Full size goal", "Bibs (2 colors)"],
    pitchSetup: "Half pitch, full goal, cones marking the overlap lane.",
    instructions: "The wide player drives inside. The fullback overlaps and delivers. Near and far runners attack the cross.",
    coachingPoints: ["Timing of the overlap", "Decide the cross before the byline", "Attack the near space first"],
    progressions: ["Defend with a full back who can jump the overlap.", "Ask for a cutback instead of a cross."],
  }),
  drill({
    id: "dr-12",
    age: "Under 17",
    moment: "OOP",
    type: "PoP",
    focus: "High Press",
    playerSetup: "Back Four",
    constraint: "One Trigger",
    level: "Senior Amateur",
    diagram: "press",
    minutes: 7,
    dimensions: "Half pitch",
    workRest: "4 min work / 1 min rest",
    repetitions: 2,
    players: count(6, 5, 0, 1),
    equipment: ["Balls", "Full size goal", "Bibs (2 colors)"],
    pitchSetup: "Half pitch, goalkeeper and back four against six.",
    instructions: "The press starts on a backwards pass or a poor first touch. Jump together, then recover if the ball goes wide.",
    coachingPoints: ["One trigger, everyone jumps", "Cover the inside pass", "Recover in a line"],
    progressions: ["Press only a backwards pass.", "Add a midfield screen behind the first line."],
  }),
  drill({
    id: "dr-13",
    age: "Under 15",
    moment: "IP",
    type: "PoP",
    focus: "Playing Out",
    playerSetup: "GK and Backs",
    constraint: "Pivot",
    level: "Youth U13-16",
    diagram: "press",
    minutes: 8,
    dimensions: "Half pitch",
    workRest: "8 min block",
    repetitions: 1,
    players: count(6, 3, 0, 1),
    equipment: ["Balls", "Full size goal", "Bibs (2 colors)"],
    pitchSetup: "Half pitch with a goalkeeper, back four, and a pivot.",
    instructions: "Goalkeeper plays into the build. The pivot shows between the lines. Restart if the press wins it.",
    coachingPoints: ["Split the centre-backs", "Pivot on the half-turn", "Play forward when the picture is on"],
    progressions: ["The press starts one player higher.", "The pivot must play first time."],
  }),
  drill({
    id: "dr-14",
    age: "Under 17",
    moment: "T2A",
    type: "PoP",
    focus: "Counter Attack",
    playerSetup: "Two Goals",
    constraint: "8 Seconds",
    level: "Senior Amateur",
    diagram: "channel",
    minutes: 7,
    dimensions: "Full width",
    workRest: "7 min block",
    repetitions: 1,
    players: count(4, 4, 0, 2),
    equipment: ["Balls", "Full size goals", "Bibs (2 colors)"],
    pitchSetup: "Full width, two goals, a halfway line as the trigger.",
    instructions: "Win the ball and attack the far goal within eight seconds. If the move stalls, reset.",
    coachingPoints: ["First pass forward", "Run beyond the ball", "Finish or cross before the extra defender arrives"],
    progressions: ["Shorten the count to six seconds.", "The team that loses the ball must counter-press for three seconds."],
  }),
  drill({
    id: "dr-15",
    age: "Under 13",
    moment: "IP",
    type: "PoP",
    focus: "Switch of Play",
    playerSetup: "Half Pitch",
    constraint: "Weak Side",
    level: "Youth U13-16",
    diagram: "square",
    minutes: 6,
    dimensions: "Half pitch",
    workRest: "6 min block",
    repetitions: 1,
    players: count(6, 4, 0, 0),
    equipment: ["Cones", "Balls", "Mini goals", "Bibs (2 colors)"],
    pitchSetup: "Half pitch with two wide goals and a central square.",
    instructions: "Play through the square, then switch to the weak side and finish in the wide goal.",
    coachingPoints: ["See the switch early", "Driven pass across", "Weak-side player is already wide"],
    progressions: ["The switch must be one pass.", "Add a defender who can jump the switch."],
  }),
  drill({
    id: "dr-16",
    age: "Under 17",
    moment: "T2D",
    type: "PoP",
    focus: "Rest Defence",
    playerSetup: "Six v Three",
    constraint: "Delay",
    level: "Senior Amateur",
    diagram: "press",
    minutes: 7,
    dimensions: "Half pitch",
    workRest: "4 min work / 1 min rest",
    repetitions: 2,
    players: count(6, 6, 0, 1),
    equipment: ["Balls", "Full size goal", "Bibs (2 colors)"],
    pitchSetup: "Half pitch, attacking six and a rest-defence three.",
    instructions: "Attack the big goal. On a loss, the three nearest players delay the counter while the rest recover.",
    coachingPoints: ["Delay, do not dive in", "Protect the centre", "Recover behind the ball"],
    progressions: ["The counter has six seconds.", "One of the three may jump if the first pass is backwards."],
  }),
  drill({
    id: "dr-17",
    age: "Under 13",
    moment: "T2D",
    type: "Physical",
    focus: "Sprint Recover",
    playerSetup: "Gates",
    constraint: "Match Rest",
    level: "Youth U13-16",
    diagram: "gates",
    minutes: 4,
    dimensions: "20m",
    workRest: "Sprint / jog back",
    repetitions: 6,
    players: none,
    equipment: ["Cones"],
    pitchSetup: "Two gates 20m apart.",
    instructions: "Sprint through the far gate, jog back, and repeat. Rest matches the work.",
    coachingPoints: ["First three steps", "Stay tall on the jog", "Stop if the sprint shape breaks"],
    progressions: ["Shorten the rest.", "Add a ball pickup at the far gate."],
  }),
  drill({
    id: "dr-18",
    age: "Under 15",
    moment: "T2A",
    type: "Physical",
    focus: "Repeated Sprints",
    playerSetup: "Lanes",
    constraint: "8 Reps",
    level: "Youth U13-16",
    diagram: "lanes",
    minutes: 5,
    dimensions: "30m lanes",
    workRest: "Sprint / walk back",
    repetitions: 8,
    players: none,
    equipment: ["Cones"],
    pitchSetup: "Four 30m lanes. One player per lane.",
    instructions: "Sprint the lane, walk back, and go again on the whistle. Eight reps.",
    coachingPoints: ["Full effort each rep", "Walk the recovery", "Same start position every time"],
    progressions: ["Cut the walk.", "Finish each sprint with a shot."],
  }),
  drill({
    id: "dr-19",
    age: "Under 11",
    moment: "IP",
    type: "WU",
    focus: "Agility Square",
    playerSetup: "One Player",
    constraint: "Low Hips",
    level: "Youth U9-12",
    diagram: "square",
    minutes: 4,
    dimensions: "5x5m",
    workRest: "30 sec work / 30 sec rest",
    repetitions: 4,
    players: none,
    equipment: ["Cones"],
    pitchSetup: "5m square, one cone per corner.",
    instructions: "Sprint one side, shuffle the next, backpedal, then sprint out. Rotate the pattern.",
    coachingPoints: ["Low hips on the shuffle", "Quick feet at the cone", "Eyes forward"],
    progressions: ["Add a ball on the last sprint.", "Call the next pattern late."],
  }),
  drill({
    id: "dr-20",
    age: "Under 13",
    moment: "IP",
    type: "Physical",
    focus: "Change Direction",
    playerSetup: "Zigzag",
    constraint: "Plant Foot",
    level: "Youth U13-16",
    diagram: "gates",
    minutes: 5,
    dimensions: "8m gaps",
    workRest: "Sprint / walk back",
    repetitions: 6,
    players: none,
    equipment: ["Cones"],
    pitchSetup: "Three gates in a zigzag, 8m apart.",
    instructions: "Sprint through each gate and plant the outside foot to change direction.",
    coachingPoints: ["Plant and push", "Ball of the foot", "Arms help the turn"],
    progressions: ["Carry a ball through the gates.", "Shorten the gaps."],
  }),
  drill({
    id: "dr-21",
    age: "Under 17",
    moment: "IP",
    type: "Physical",
    focus: "Tempo Runs",
    playerSetup: "Full Width",
    constraint: "Walk Back",
    level: "Senior Amateur",
    diagram: "lanes",
    minutes: 8,
    dimensions: "Touchline to touchline",
    workRest: "Run the width / walk the line",
    repetitions: 6,
    players: none,
    equipment: ["Cones"],
    pitchSetup: "Touchline to touchline, full width.",
    instructions: "Run the width at tempo, walk the goal line, and repeat for the block.",
    coachingPoints: ["Even pace", "Breathe out on the walk", "Stay in the lane"],
    progressions: ["Raise the tempo on the last two.", "Add a ball at one touchline."],
  }),
  drill({
    id: "dr-22",
    age: "Under 11",
    moment: "IP",
    type: "WU",
    focus: "Jump and Land",
    playerSetup: "Hurdles",
    constraint: "Soft Landing",
    level: "Youth U9-12",
    diagram: "gates",
    minutes: 4,
    dimensions: "Line of hurdles",
    workRest: "4 jumps / walk back",
    repetitions: 4,
    players: none,
    equipment: ["Cones", "Low hurdles"],
    pitchSetup: "A line of low hurdles or cones, with a landing square after each.",
    instructions: "Jump the hurdle and land soft on two feet inside the square.",
    coachingPoints: ["Quiet landing", "Knees over toes", "Hold the landing before the next jump"],
    progressions: ["Land on one foot.", "Sprint out of the last landing."],
  }),
  drill({
    id: "dr-23",
    age: "Under 15",
    moment: "OOP",
    type: "Physical",
    focus: "Press and Recover",
    playerSetup: "Mannequins",
    constraint: "Sprint",
    level: "Youth U13-16",
    diagram: "press",
    minutes: 5,
    dimensions: "Half pitch",
    workRest: "Press / sprint back",
    repetitions: 6,
    players: none,
    equipment: ["Mannequins", "Cones"],
    pitchSetup: "Half pitch with mannequins as the press points.",
    instructions: "Close down the mannequin, then sprint back to the recovery cone.",
    coachingPoints: ["Arrive on the angle", "Do not overrun", "Recover at full speed"],
    progressions: ["Press two mannequins before recovering.", "Recover with a ball."],
  }),
  drill({
    id: "dr-24",
    age: "Under 17",
    moment: "IP",
    type: "SSG",
    focus: "Conditioning",
    playerSetup: "4v4",
    constraint: "Sprint on Goal",
    level: "Senior Amateur",
    diagram: "rondo",
    minutes: 8,
    dimensions: "30x20m",
    workRest: "Play to a goal, then sprint",
    repetitions: 1,
    players: count(4, 4),
    equipment: ["Bibs (2 colors)", "Ball", "Mini goals", "Cones"],
    pitchSetup: "30m box, 4v4, two small goals.",
    instructions: "Play until a goal, then the scorers sprint the width before the restart.",
    coachingPoints: ["Work after the goal", "Restart quickly", "Keep the press"],
    progressions: ["Both teams sprint after a goal.", "Limit every player to two touches."],
  }),
  drill({
    id: "dr-25",
    age: "Under 15",
    moment: "IP",
    type: "PoP",
    focus: "Corner Attack",
    playerSetup: "6v4+GK",
    constraint: "Fast Restart",
    level: "Youth U13-16",
    diagram: "corner",
    minutes: 6,
    dimensions: "Corner arc",
    workRest: "6 min block",
    repetitions: 1,
    players: count(6, 4, 0, 1),
    equipment: ["Balls", "Full size goal", "Bibs (2 colors)"],
    pitchSetup: "One corner arc, six attackers, four defenders, goalkeeper.",
    instructions: "Call the delivery, then attack near post, penalty spot, and back post. Restart quickly.",
    coachingPoints: ["Deliver to a zone", "Attack the ball", "Set the second-ball shape"],
    progressions: ["Inswinging only.", "The defending team breaks out if they win the first ball."],
  }),
  drill({
    id: "dr-26",
    age: "Under 13",
    moment: "IP",
    type: "PoP",
    focus: "Near Post Corner",
    playerSetup: "3 Runners",
    constraint: "Inswing",
    level: "Youth U13-16",
    diagram: "corner",
    minutes: 6,
    dimensions: "Corner arc",
    workRest: "6 min block",
    repetitions: 1,
    players: count(4, 2, 0, 1),
    equipment: ["Balls", "Full size goal"],
    pitchSetup: "Corner flag, one runner on the near post, two on the edge.",
    instructions: "Inswinging delivery to the near post. The runner glances or flicks across.",
    coachingPoints: ["Pace on the cross", "Run across the keeper", "Edge players attack the second ball"],
    progressions: ["Add a defender on the near post.", "Change to an outswinging delivery."],
  }),
  drill({
    id: "dr-27",
    age: "Under 17",
    moment: "IP",
    type: "PoP",
    focus: "Short Corner",
    playerSetup: "2 Takers",
    constraint: "Decoy Run",
    level: "Senior Amateur",
    diagram: "corner",
    minutes: 6,
    dimensions: "Corner arc",
    workRest: "6 min block",
    repetitions: 1,
    players: count(5, 4, 0, 1),
    equipment: ["Balls", "Full size goal", "Cones", "Bibs (2 colors)"],
    pitchSetup: "Corner arc with a short option 8m inside.",
    instructions: "Play short, then combine to cross or shoot. The decoy still attacks the near post.",
    coachingPoints: ["Short pass quality", "Decoy run is real", "Decision before the cross"],
    progressions: ["The short pass can be returned first time.", "A defender may jump the short option."],
  }),
  drill({
    id: "dr-28",
    age: "Under 17",
    moment: "IP",
    type: "PoP",
    focus: "Direct Free Kick",
    playerSetup: "2 Takers",
    constraint: "Wall",
    level: "Senior Amateur",
    diagram: "channel",
    minutes: 6,
    dimensions: "Free-kick range",
    workRest: "3 kicks, then rotate",
    repetitions: 3,
    players: count(2, 2, 0, 1),
    equipment: ["Balls", "Full size goal"],
    pitchSetup: "Free-kick range, a two-player wall, goalkeeper.",
    instructions: "Two takers. One strikes, one is ready for the layoff. Rotate after three kicks.",
    coachingPoints: ["Plant foot aimed", "Strike through the ball", "Wall jump is timed"],
    progressions: ["Add a runner for the layoff.", "Move the kick wider."],
  }),
  drill({
    id: "dr-29",
    age: "Under 15",
    moment: "IP",
    type: "PoP",
    focus: "Wide Free Kick",
    playerSetup: "Box Runners",
    constraint: "Back Post",
    level: "Youth U13-16",
    diagram: "overlap",
    minutes: 6,
    dimensions: "Wide channel",
    workRest: "6 min block",
    repetitions: 1,
    players: count(4, 3, 0, 1),
    equipment: ["Balls", "Full size goal", "Bibs (2 colors)"],
    pitchSetup: "Free kick from the wide channel, a wall, and two box runners.",
    instructions: "Deliver to the back-post runner or pull it back to the edge.",
    coachingPoints: ["See the keeper's position", "Back-post run starts late", "Edge player is set"],
    progressions: ["Near-post run only.", "Add a short option before the cross."],
  }),
  drill({
    id: "dr-30",
    age: "Under 13",
    moment: "IP",
    type: "PoP",
    focus: "Throw-in",
    playerSetup: "Runner",
    constraint: "Down the Line",
    level: "Youth U13-16",
    diagram: "overlap",
    minutes: 5,
    dimensions: "Touchline",
    workRest: "5 min block",
    repetitions: 1,
    players: count(3, 1),
    equipment: ["Balls", "Cones"],
    pitchSetup: "Touchline, thrower, a checking runner, and a target.",
    instructions: "Throw into the runner's feet or down the line for them to attack.",
    coachingPoints: ["Thrower shows the target", "Runner checks then spins", "First touch forward"],
    progressions: ["Throw must go down the line.", "Add a second defender."],
  }),
  drill({
    id: "dr-31",
    age: "Under 11",
    moment: "IP",
    type: "PoP",
    focus: "Goal Kick Build",
    playerSetup: "GK and Backs",
    constraint: "Simple",
    level: "Youth U9-12",
    diagram: "press",
    minutes: 6,
    dimensions: "Defensive third",
    workRest: "6 min block",
    repetitions: 1,
    players: count(3, 1, 0, 1),
    equipment: ["Balls", "Full size goal", "Bibs"],
    pitchSetup: "Goalkeeper, two centre-backs, and a pressing forward.",
    instructions: "Goal kick to a centre-back, who plays into the midfielder. Restart if the press wins it.",
    coachingPoints: ["Centre-back body shape", "Goalkeeper has a second option", "Play simple under pressure"],
    progressions: ["The press starts on the goalkeeper.", "Add a second pressing player."],
  }),
  drill({
    id: "dr-32",
    age: "Under 15",
    moment: "OOP",
    type: "PoP",
    focus: "Defend the Corner",
    playerSetup: "Back Four",
    constraint: "Clear Wide",
    level: "Youth U13-16",
    diagram: "corner",
    minutes: 6,
    dimensions: "Corner arc",
    workRest: "6 min block",
    repetitions: 1,
    players: count(6, 4, 0, 1),
    equipment: ["Balls", "Full size goal", "Bibs (2 colors)"],
    pitchSetup: "Same corner setup, focus on the defending four and the keeper.",
    instructions: "Mark zones, attack the ball, and clear to the side. Then set the rest defence.",
    coachingPoints: ["Attack the ball, do not watch it", "Keeper owns the six-yard box", "First clear is wide"],
    progressions: ["Man-mark the near post.", "Break out within five seconds of the clear."],
  }),
];
